# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0004_auto_20190603_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
