# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0005_auto_20190603_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.CharField(max_length=100)),
            ],
        ),
    ]
